import { createMutation, createQuery, createQueryFactory } from "@ic-reactor/react"
import { backendReactor } from "./index.generated"

/**
 * Backend Query and Mutation Factories
 *
 * Auto-generated by @ic-reactor/codegen — do not edit.
 * This file is overwritten whenever generation runs.
 *
 * One export per method of the service, bound to `backendReactor`:
 * `createQuery` for a query method that takes no arguments,
 * `createQueryFactory` for a query method that takes arguments, and
 * `createMutation` for an update or oneway method. Pass per-call options to
 * `useQuery()` and `useMutation()`, and define a factory with its own
 * config in the stable `index.ts` wrapper (or an adjacent module).
 */

/** "ai_assist": update. */
export const aiAssistMutation = /* @__PURE__ */ createMutation(backendReactor, {
  functionName: "ai_assist",
})

/** "create_note": update. */
export const createNoteMutation = /* @__PURE__ */ createMutation(backendReactor, {
  functionName: "create_note",
})

/** "create_share": update. */
export const createShareMutation = /* @__PURE__ */ createMutation(backendReactor, {
  functionName: "create_share",
})

/** "delete_account": update. */
export const deleteAccountMutation = /* @__PURE__ */ createMutation(backendReactor, {
  functionName: "delete_account",
})

/** "delete_note": update. */
export const deleteNoteMutation = /* @__PURE__ */ createMutation(backendReactor, {
  functionName: "delete_note",
})

/** "get_account": query, no arguments. */
export const getAccountQuery = /* @__PURE__ */ createQuery(backendReactor, {
  functionName: "get_account",
})

/** "get_config": query, no arguments. */
export const getConfigQuery = /* @__PURE__ */ createQuery(backendReactor, {
  functionName: "get_config",
})

/** "get_encrypted_user_key": update. */
export const getEncryptedUserKeyMutation = /* @__PURE__ */ createMutation(backendReactor, {
  functionName: "get_encrypted_user_key",
})

/** "get_note": query. `getNoteQuery(args)` is the query for those arguments. */
export const getNoteQuery = /* @__PURE__ */ createQueryFactory(backendReactor, {
  functionName: "get_note",
})

/** "get_public_keys": query, no arguments. */
export const getPublicKeysQuery = /* @__PURE__ */ createQuery(backendReactor, {
  functionName: "get_public_keys",
})

/** "get_share": query. `getShareQuery(args)` is the query for those arguments. */
export const getShareQuery = /* @__PURE__ */ createQueryFactory(backendReactor, {
  functionName: "get_share",
})

/** "get_stats": query, no arguments. */
export const getStatsQuery = /* @__PURE__ */ createQuery(backendReactor, {
  functionName: "get_stats",
})

/** "list_notes": query. `listNotesQuery(args)` is the query for those arguments. */
export const listNotesQuery = /* @__PURE__ */ createQueryFactory(backendReactor, {
  functionName: "list_notes",
})

/** "list_shares": query, no arguments. */
export const listSharesQuery = /* @__PURE__ */ createQuery(backendReactor, {
  functionName: "list_shares",
})

/** "load_public_keys": update. */
export const loadPublicKeysMutation = /* @__PURE__ */ createMutation(backendReactor, {
  functionName: "load_public_keys",
})

/** "open_share": update. */
export const openShareMutation = /* @__PURE__ */ createMutation(backendReactor, {
  functionName: "open_share",
})

/** "revoke_share": update. */
export const revokeShareMutation = /* @__PURE__ */ createMutation(backendReactor, {
  functionName: "revoke_share",
})

/** "update_config": update. */
export const updateConfigMutation = /* @__PURE__ */ createMutation(backendReactor, {
  functionName: "update_config",
})

/** "update_note": update. */
export const updateNoteMutation = /* @__PURE__ */ createMutation(backendReactor, {
  functionName: "update_note",
})

/** "whoami": query, no arguments. */
export const whoamiQuery = /* @__PURE__ */ createQuery(backendReactor, {
  functionName: "whoami",
})
