// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

type $Account = { principal: $.Principal; share_count: number; ai_enabled: boolean; created_at: bigint; note_count: number; storage_bytes: bigint; ai_model: string; limits: $Limits };
const $Account: $.Schema<$Account> = $.c.rec(() => $.c.record({ principal: $.c.principal, share_count: $.c.nat32, ai_enabled: $.c.bool, created_at: $.c.nat64, note_count: $.c.nat32, storage_bytes: $.c.nat64, ai_model: $.c.text, limits: $Limits }));
export { $Account as Account };

type $AiRequest = { task: $AiTask; text: string };
const $AiRequest: $.Schema<$AiRequest> = $.c.rec(() => $.c.record({ task: $AiTask, text: $.c.text }));
export { $AiRequest as AiRequest };

type $AiResponse = { model: string; text: string };
const $AiResponse: $.Schema<$AiResponse> = $.c.rec(() => $.c.record({ model: $.c.text, text: $.c.text }));
export { $AiResponse as AiResponse };

/** What the AI assistant should do with the text. */
type $AiTask =
  | {
      /** Answer a question using the text (the user's notes) as context. */
      tag: "Ask";
      value: string;
    }
  | {
      /** More text in the same style. */
      tag: "Continue";
    }
  | {
      /** Spelling and grammar only. */
      tag: "FixGrammar";
    }
  | {
      /** Clearer, better structured wording. */
      tag: "Improve";
    }
  | {
      /** A shorter version. */
      tag: "Shorten";
    }
  | {
      /** A markdown checklist of the action items. */
      tag: "ActionItems";
    }
  | {
      /** A title of a few words. */
      tag: "SuggestTitle";
    }
  | {
      /** A translation into the named language. */
      tag: "Translate";
      value: string;
    }
  | {
      /** Comma-separated topic tags. */
      tag: "SuggestTags";
    }
  | {
      /** A short summary. */
      tag: "Summarize";
    };
/** What the AI assistant should do with the text. */
const $AiTask: $.Schema<$AiTask> = $.c.rec(() => $.c.variant({ Ask: $.c.text, Continue: $.c.null, FixGrammar: $.c.null, Improve: $.c.null, Shorten: $.c.null, ActionItems: $.c.null, SuggestTitle: $.c.null, Translate: $.c.text, SuggestTags: $.c.null, Summarize: $.c.null }));
export { $AiTask as AiTask };

/** The canister configuration. */
type $Config = {
  ai_enabled: boolean;
  /** Cycles attached to each LLM call (0 for the free models). */
  llm_cycles_per_call: bigint;
  llm_model: string;
  /**
   * The LLM canister. `None` resolves `PUBLIC_CANISTER_ID:llm` (set by
   * `icp deploy`) and falls back to the mainnet LLM canister.
   */
  llm_canister: $.Principal | null;
  limits: $Limits;
  /**
   * Name of the vetKD master key: `key_1` on mainnet, `test_key_1` or
   * `dfx_test_key` on a local network.
   */
  vetkd_key_name: string;
};
/** The canister configuration. */
const $Config: $.Schema<$Config> = $.c.rec(() => $.c.record({ ai_enabled: $.c.bool, llm_cycles_per_call: $.c.nat64, llm_model: $.c.text, llm_canister: $.c.opt($.c.principal), limits: $Limits, vetkd_key_name: $.c.text }));
export { $Config as Config };

type $CreateNoteArgs = { id: string; ciphertext: Uint8Array; expires_at: bigint | null };
const $CreateNoteArgs: $.Schema<$CreateNoteArgs> = $.c.rec(() => $.c.record({ id: $.c.text, ciphertext: $.c.blob(), expires_at: $.c.opt($.c.nat64) }));
export { $CreateNoteArgs as CreateNoteArgs };

type $CreateShareArgs = {
  /** 32 lowercase hex characters (16 random bytes chosen by the client). */
  id: string;
  /** Ed25519 public key (32 bytes) whose secret key travels in the link. */
  verifying_key: Uint8Array;
  /** IBE ciphertext for the identity `id`, under `PublicKeys.share_key`. */
  ciphertext: Uint8Array;
  max_views: number;
  /** The note this share was created from, so deleting it revokes the share. */
  note_id: string | null;
  expires_in_secs: bigint;
};
const $CreateShareArgs: $.Schema<$CreateShareArgs> = $.c.rec(() => $.c.record({ id: $.c.text, verifying_key: $.c.blob(), ciphertext: $.c.blob(), max_views: $.c.nat32, note_id: $.c.opt($.c.text), expires_in_secs: $.c.nat64 }));
export { $CreateShareArgs as CreateShareArgs };

type $DeletedAccount = { shares: number; notes: number };
const $DeletedAccount: $.Schema<$DeletedAccount> = $.c.rec(() => $.c.record({ shares: $.c.nat32, notes: $.c.nat32 }));
export { $DeletedAccount as DeletedAccount };

/** The owner's encrypted vetKey and the public key to verify it with. */
type $EncryptedUserKey = { encrypted_key: Uint8Array; verification_key: Uint8Array };
/** The owner's encrypted vetKey and the public key to verify it with. */
const $EncryptedUserKey: $.Schema<$EncryptedUserKey> = $.c.rec(() => $.c.record({ encrypted_key: $.c.blob(), verification_key: $.c.blob() }));
export { $EncryptedUserKey as EncryptedUserKey };

/** Errors returned by every fallible endpoint. */
type $Error =
  | {
      /** The call to the LLM canister failed. */
      tag: "Ai";
      value: string;
    }
  | {
      /** The share link has no views left. */
      tag: "Exhausted";
    }
  | {
      /** The public keys have not been fetched from the management canister yet. */
      tag: "NotReady";
    }
  | { tag: "NotFound" }
  | { tag: "AlreadyExists" }
  | {
      /** Too many requests; retry after the given number of seconds. */
      tag: "RateLimited";
      value: { retry_after_secs: bigint };
    }
  | {
      /** AI features are disabled on this deployment. */
      tag: "AiDisabled";
    }
  | { tag: "InvalidArgument"; value: string }
  | {
      /** A call to the vetKD system API failed. */
      tag: "VetKd";
      value: string;
    }
  | {
      /** The caller is not allowed to perform this action. */
      tag: "Forbidden";
      value: string;
    }
  | {
      /** The share link or note has expired. */
      tag: "Expired";
    }
  | {
      /** A per-user or global quota would be exceeded. */
      tag: "QuotaExceeded";
      value: string;
    }
  | {
      /** The caller must sign in (anonymous callers are not allowed here). */
      tag: "Unauthenticated";
    }
  | {
      /** The note changed since the caller last read it. */
      tag: "Conflict";
      value: { current_version: bigint };
    };
/** Errors returned by every fallible endpoint. */
const $Error: $.Schema<$Error> = $.c.rec(() => $.c.variant({ Ai: $.c.text, Exhausted: $.c.null, NotReady: $.c.null, NotFound: $.c.null, AlreadyExists: $.c.null, RateLimited: $.c.record({ retry_after_secs: $.c.nat64 }), AiDisabled: $.c.null, InvalidArgument: $.c.text, VetKd: $.c.text, Forbidden: $.c.text, Expired: $.c.null, QuotaExceeded: $.c.text, Unauthenticated: $.c.null, Conflict: $.c.record({ current_version: $.c.nat64 }) }));
export { $Error as Error };

/**
 * Install and upgrade arguments. Every field is optional; `None` keeps the
 * current (or default) value.
 */
type $InitArgs = { ai_enabled: boolean | null; llm_cycles_per_call: bigint | null; llm_model: string | null; llm_canister: $.Principal | null; limits: $Limits | null; vetkd_key_name: string | null };
/**
 * Install and upgrade arguments. Every field is optional; `None` keeps the
 * current (or default) value.
 */
const $InitArgs: $.Schema<$InitArgs> = $.c.rec(() => $.c.record({ ai_enabled: $.c.opt($.c.bool), llm_cycles_per_call: $.c.opt($.c.nat64), llm_model: $.c.opt($.c.text), llm_canister: $.c.opt($.c.principal), limits: $.c.opt($Limits), vetkd_key_name: $.c.opt($.c.text) }));
export { $InitArgs as InitArgs };

/** Hard limits enforced by the canister. Controllers can change them. */
type $Limits = {
  /** Maximum size of one encrypted note, in bytes. */
  max_note_bytes: number;
  /** vetKD derivations (user key + share opens) one principal may request per hour. */
  key_requests_per_user_per_hour: number;
  ai_requests_per_user_per_hour: number;
  /** vetKD derivations the whole canister may request per hour (protects its cycles). */
  global_key_requests_per_hour: number;
  max_share_ttl_secs: bigint;
  max_share_views: number;
  max_notes_per_user: number;
  /** Maximum number of UTF-8 bytes sent to the LLM in one request. */
  max_ai_input_bytes: number;
  max_shares_per_user: number;
  global_ai_requests_per_hour: number;
};
/** Hard limits enforced by the canister. Controllers can change them. */
const $Limits: $.Schema<$Limits> = $.c.rec(() => $.c.record({ max_note_bytes: $.c.nat32, key_requests_per_user_per_hour: $.c.nat32, ai_requests_per_user_per_hour: $.c.nat32, global_key_requests_per_hour: $.c.nat32, max_share_ttl_secs: $.c.nat64, max_share_views: $.c.nat32, max_notes_per_user: $.c.nat32, max_ai_input_bytes: $.c.nat32, max_shares_per_user: $.c.nat32, global_ai_requests_per_hour: $.c.nat32 }));
export { $Limits as Limits };

type $ListNotesArgs = {
  /** Return notes whose id sorts after this one. */
  cursor: string | null;
  limit: number | null;
};
const $ListNotesArgs: $.Schema<$ListNotesArgs> = $.c.rec(() => $.c.record({ cursor: $.c.opt($.c.text), limit: $.c.opt($.c.nat32) }));
export { $ListNotesArgs as ListNotesArgs };

/** An encrypted note as stored by the canister. */
type $Note = {
  /** 32 lowercase hex characters (16 random bytes chosen by the client). */
  id: string;
  updated_at: bigint;
  /** AES-GCM ciphertext produced with the owner's vetKey-derived key. */
  ciphertext: Uint8Array;
  created_at: bigint;
  /** Incremented on every update, for optimistic concurrency control. */
  version: bigint;
  /** The note deletes itself at this time (nanoseconds since the epoch). */
  expires_at: bigint | null;
};
/** An encrypted note as stored by the canister. */
const $Note: $.Schema<$Note> = $.c.rec(() => $.c.record({ id: $.c.text, updated_at: $.c.nat64, ciphertext: $.c.blob(), created_at: $.c.nat64, version: $.c.nat64, expires_at: $.c.opt($.c.nat64) }));
export { $Note as Note };

type $NotePage = { notes: Array<$Note>; next_cursor: string | null };
const $NotePage: $.Schema<$NotePage> = $.c.rec(() => $.c.record({ notes: $.c.vec($Note), next_cursor: $.c.opt($.c.text) }));
export { $NotePage as NotePage };

type $OpenShareArgs = {
  id: string;
  /** Ed25519 signature over `SHARE_OPEN_DOMAIN || id bytes || transport_public_key`. */
  signature: Uint8Array;
  /** A fresh BLS12-381 G1 transport public key (48 bytes). */
  transport_public_key: Uint8Array;
};
const $OpenShareArgs: $.Schema<$OpenShareArgs> = $.c.rec(() => $.c.record({ id: $.c.text, signature: $.c.blob(), transport_public_key: $.c.blob() }));
export { $OpenShareArgs as OpenShareArgs };

type $OpenedShare = {
  views_left: number;
  /** The vetKey for the share id, encrypted to the transport public key. */
  encrypted_key: Uint8Array;
  ciphertext: Uint8Array;
  verification_key: Uint8Array;
  expires_at: bigint;
};
const $OpenedShare: $.Schema<$OpenedShare> = $.c.rec(() => $.c.record({ views_left: $.c.nat32, encrypted_key: $.c.blob(), ciphertext: $.c.blob(), verification_key: $.c.blob(), expires_at: $.c.nat64 }));
export { $OpenedShare as OpenedShare };

/** Derived public keys of this canister. */
type $PublicKeys = {
  /** Verifies users' vetKeys (input: the user's principal). */
  user_key: Uint8Array;
  /** IBE-encrypts share payloads (identity: the share id). */
  share_key: Uint8Array;
};
/** Derived public keys of this canister. */
const $PublicKeys: $.Schema<$PublicKeys> = $.c.rec(() => $.c.record({ user_key: $.c.blob(), share_key: $.c.blob() }));
export { $PublicKeys as PublicKeys };

/** What anyone holding a share id may learn before opening it. */
type $PublicShareInfo = { views_left: number; size: number; created_at: bigint; expires_at: bigint };
/** What anyone holding a share id may learn before opening it. */
const $PublicShareInfo: $.Schema<$PublicShareInfo> = $.c.rec(() => $.c.record({ views_left: $.c.nat32, size: $.c.nat32, created_at: $.c.nat64, expires_at: $.c.nat64 }));
export { $PublicShareInfo as PublicShareInfo };

type $Result = { tag: "Ok"; value: $AiResponse } | { tag: "Err"; value: $Error };
const $Result: $.Schema<$Result> = $.c.rec(() => $.c.variant({ Ok: $AiResponse, Err: $Error }));
export { $Result as Result };

type $Result_1 = { tag: "Ok"; value: $Note } | { tag: "Err"; value: $Error };
const $Result_1: $.Schema<$Result_1> = $.c.rec(() => $.c.variant({ Ok: $Note, Err: $Error }));
export { $Result_1 as Result_1 };

type $Result_10 = { tag: "Ok"; value: Array<$ShareInfo> } | { tag: "Err"; value: $Error };
const $Result_10: $.Schema<$Result_10> = $.c.rec(() => $.c.variant({ Ok: $.c.vec($ShareInfo), Err: $Error }));
export { $Result_10 as Result_10 };

type $Result_11 = { tag: "Ok"; value: $OpenedShare } | { tag: "Err"; value: $Error };
const $Result_11: $.Schema<$Result_11> = $.c.rec(() => $.c.variant({ Ok: $OpenedShare, Err: $Error }));
export { $Result_11 as Result_11 };

type $Result_12 = { tag: "Ok"; value: $Config } | { tag: "Err"; value: $Error };
const $Result_12: $.Schema<$Result_12> = $.c.rec(() => $.c.variant({ Ok: $Config, Err: $Error }));
export { $Result_12 as Result_12 };

type $Result_2 = { tag: "Ok"; value: $ShareInfo } | { tag: "Err"; value: $Error };
const $Result_2: $.Schema<$Result_2> = $.c.rec(() => $.c.variant({ Ok: $ShareInfo, Err: $Error }));
export { $Result_2 as Result_2 };

type $Result_3 = { tag: "Ok"; value: $DeletedAccount } | { tag: "Err"; value: $Error };
const $Result_3: $.Schema<$Result_3> = $.c.rec(() => $.c.variant({ Ok: $DeletedAccount, Err: $Error }));
export { $Result_3 as Result_3 };

type $Result_4 = { tag: "Ok" } | { tag: "Err"; value: $Error };
const $Result_4: $.Schema<$Result_4> = $.c.rec(() => $.c.variant({ Ok: $.c.null, Err: $Error }));
export { $Result_4 as Result_4 };

type $Result_5 = { tag: "Ok"; value: $Account } | { tag: "Err"; value: $Error };
const $Result_5: $.Schema<$Result_5> = $.c.rec(() => $.c.variant({ Ok: $Account, Err: $Error }));
export { $Result_5 as Result_5 };

type $Result_6 = { tag: "Ok"; value: $EncryptedUserKey } | { tag: "Err"; value: $Error };
const $Result_6: $.Schema<$Result_6> = $.c.rec(() => $.c.variant({ Ok: $EncryptedUserKey, Err: $Error }));
export { $Result_6 as Result_6 };

type $Result_7 = { tag: "Ok"; value: $PublicKeys } | { tag: "Err"; value: $Error };
const $Result_7: $.Schema<$Result_7> = $.c.rec(() => $.c.variant({ Ok: $PublicKeys, Err: $Error }));
export { $Result_7 as Result_7 };

type $Result_8 = { tag: "Ok"; value: $PublicShareInfo } | { tag: "Err"; value: $Error };
const $Result_8: $.Schema<$Result_8> = $.c.rec(() => $.c.variant({ Ok: $PublicShareInfo, Err: $Error }));
export { $Result_8 as Result_8 };

type $Result_9 = { tag: "Ok"; value: $NotePage } | { tag: "Err"; value: $Error };
const $Result_9: $.Schema<$Result_9> = $.c.rec(() => $.c.variant({ Ok: $NotePage, Err: $Error }));
export { $Result_9 as Result_9 };

/** A share as its owner sees it. */
type $ShareInfo = { id: string; views_left: number; max_views: number; size: number; note_id: string | null; created_at: bigint; expires_at: bigint };
/** A share as its owner sees it. */
const $ShareInfo: $.Schema<$ShareInfo> = $.c.rec(() => $.c.record({ id: $.c.text, views_left: $.c.nat32, max_views: $.c.nat32, size: $.c.nat32, note_id: $.c.opt($.c.text), created_at: $.c.nat64, expires_at: $.c.nat64 }));
export { $ShareInfo as ShareInfo };

type $Stats = { ai_enabled: boolean; active_shares: bigint; version: string; cycles: bigint; notes: bigint; users: bigint; ai_model: string; vetkd_key_name: string };
const $Stats: $.Schema<$Stats> = $.c.rec(() => $.c.record({ ai_enabled: $.c.bool, active_shares: $.c.nat64, version: $.c.text, cycles: $.c.nat, notes: $.c.nat64, users: $.c.nat64, ai_model: $.c.text, vetkd_key_name: $.c.text }));
export { $Stats as Stats };

type $UpdateNoteArgs = {
  id: string;
  ciphertext: Uint8Array;
  /** Replaces the note's expiry (`None` removes it). */
  expires_at: bigint | null;
  /** Reject the update with `Conflict` unless the note is at this version. */
  expected_version: bigint | null;
};
const $UpdateNoteArgs: $.Schema<$UpdateNoteArgs> = $.c.rec(() => $.c.record({ id: $.c.text, ciphertext: $.c.blob(), expires_at: $.c.opt($.c.nat64), expected_version: $.c.opt($.c.nat64) }));
export { $UpdateNoteArgs as UpdateNoteArgs };

const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ revoke_share: $.c.func([$.c.text], [$Result_4], "update"), ai_assist: $.c.func([$AiRequest], [$Result], "update"), get_account: $.c.func([], [$Result_5], "query"), update_config: $.c.func([$InitArgs], [$Result_12], "update"), update_note: $.c.func([$UpdateNoteArgs], [$Result_1], "update"), delete_account: $.c.func([], [$Result_3], "update"), create_share: $.c.func([$CreateShareArgs], [$Result_2], "update"), list_shares: $.c.func([], [$Result_10], "query"), get_public_keys: $.c.func([], [$Result_7], "query"), open_share: $.c.func([$OpenShareArgs], [$Result_11], "update"), create_note: $.c.func([$CreateNoteArgs], [$Result_1], "update"), get_config: $.c.func([], [$Config], "query"), get_share: $.c.func([$.c.text], [$Result_8], "query"), whoami: $.c.func([], [$.c.principal], "query"), get_stats: $.c.func([], [$Stats], "query"), get_note: $.c.func([$.c.text], [$Result_1], "query"), list_notes: $.c.func([$ListNotesArgs], [$Result_9], "query"), load_public_keys: $.c.func([], [$Result_7], "update"), get_encrypted_user_key: $.c.func([$.c.blob()], [$Result_6], "update"), delete_note: $.c.func([$.c.text], [$Result_4], "update") }));
type $Actor = {
  revoke_share: (arg0: string) => Promise<$Result_4>;
  /** Runs one writing-assistant task on text the user chose to send. */
  ai_assist: (arg0: $AiRequest) => Promise<$Result>;
  get_account: () => Promise<$Result_5>;
  /** Changes the configuration. Controllers only. */
  update_config: (arg0: $InitArgs) => Promise<$Result_12>;
  update_note: (arg0: $UpdateNoteArgs) => Promise<$Result_1>;
  /** Deletes every note and share of the caller. */
  delete_account: () => Promise<$Result_3>;
  create_share: (arg0: $CreateShareArgs) => Promise<$Result_2>;
  list_shares: () => Promise<$Result_10>;
  /** The derived public keys, once the canister has fetched them. */
  get_public_keys: () => Promise<$Result_7>;
  /**
   * Spends one view of a share and returns its ciphertext with the share's
   * vetKey encrypted to the reader's transport key. Anyone holding the link
   * may call this; signing in is not required.
   */
  open_share: (arg0: $OpenShareArgs) => Promise<$Result_11>;
  create_note: (arg0: $CreateNoteArgs) => Promise<$Result_1>;
  get_config: () => Promise<$Config>;
  /** What a link holder sees before deciding to open (and burn) a share. */
  get_share: (arg0: string) => Promise<$Result_8>;
  whoami: () => Promise<$.Principal>;
  get_stats: () => Promise<$Stats>;
  get_note: (arg0: string) => Promise<$Result_1>;
  list_notes: (arg0: $ListNotesArgs) => Promise<$Result_9>;
  /** Like `get_public_keys`, but fetches the keys if they are not cached yet. */
  load_public_keys: () => Promise<$Result_7>;
  /**
   * The caller's vetKey, encrypted to `transport_public_key`, and the public
   * key that verifies it. The vetKey's input is the caller's principal.
   */
  get_encrypted_user_key: (arg0: Uint8Array) => Promise<$Result_6>;
  /** Deletes a note and revokes the share links made from it. */
  delete_note: (arg0: string) => Promise<$Result_4>;
};
export { $actor as actor, type $Actor as Actor };
// Note: the actor is a service class; init args are install-time metadata not exposed here (issue #104).
