"use client"
import {
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TablePagination,
  TableRow,
  Typography,
} from "@mui/material"
import Section from "components/Section"
import { fetchLogs, fetchTimers, initBackend } from "contexts/helpers"
import { useBackendIsInitialized } from "contexts/hooks/useBackend"
import { useBackendLoading } from "contexts/hooks/useLoading"
import { LogEntry, TaskTimerEntry } from "declarations/backend/backend.did"
import { nanoToHumanReadable } from "helper/utils"
import { useEffect, useState } from "react"

interface LogsProps {}

let timer: NodeJS.Timeout

const Logs: React.FC<LogsProps> = ({}) => {
  const [logs, setLogs] = useState<LogEntry[]>([])
  const [timers, setTimers] = useState<TaskTimerEntry[]>([])
  const [page, setPage] = useState(0)
  const [rowsPerPage, setRowsPerPage] = useState(10)

  const fetchingLogsLoading = useBackendLoading("fetch_logs")
  const fetchingTimerLoading = useBackendLoading("fetch_timers")

  const handleChangePage = (_: unknown, newPage: number) => {
    setPage(newPage)
  }

  const handleChangeRowsPerPage = (
    event: React.ChangeEvent<HTMLInputElement>
  ) => {
    setRowsPerPage(+event.target.value)
    setPage(0)
  }
  const backendInitailized = useBackendIsInitialized()

  useEffect(() => {
    if (backendInitailized) {
      fetchLogs().then(setLogs)
      fetchTimers().then(setTimers)
    } else {
      initBackend()
    }

    timer = setTimeout(() => {
      if (backendInitailized) fetchLogs().then(setLogs)
    }, 10000)

    return () => {
      clearTimeout(timer)
    }
  }, [backendInitailized])

  return (
    <Section
      title="Logs"
      loading={!backendInitailized}
      loadingTitle="Initializing"
    >
      <Section
        title="Timers"
        color="info"
        description="The following timers are running in the backend."
        action={() => fetchTimers().then(setTimers)}
        actionProps={{ disabled: fetchingTimerLoading }}
        noShadow
        noMargin
      >
        <TableContainer component={Paper} variant="outlined">
          <Table size="small" aria-label="simple table">
            <TableHead>
              <TableRow>
                <TableCell>Scheduled Time</TableCell>
                <TableCell>Task</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {timers.map(({ task, time }, index) => (
                <TableRow
                  key={index}
                  sx={{ "&:last-child td, &:last-child th": { border: 0 } }}
                >
                  <TableCell component="th" scope="row">
                    {nanoToHumanReadable(time)}
                  </TableCell>
                  <TableCell>{Object.keys(task)[0]}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </Section>
      <Section
        title="Logs"
        color="secondary"
        description="The following logs are generated by the backend."
        action={() => fetchLogs().then(setLogs)}
        actionProps={{ disabled: fetchingLogsLoading }}
        noShadow
        noMargin
      >
        <TableContainer component={Paper} variant="outlined">
          <Table size="small" aria-label="simple table">
            <TableHead>
              <TableRow>
                <TableCell>Time</TableCell>
                <TableCell>Event</TableCell>
                <TableCell align="right">Version</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {logs
                ?.slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage)
                .map(({ message, timestamp, version }, index) => (
                  <TableRow
                    key={index}
                    sx={{ "&:last-child td, &:last-child th": { border: 0 } }}
                  >
                    <TableCell component="th" scope="row">
                      {nanoToHumanReadable(timestamp)}
                    </TableCell>
                    <TableCell>{message}</TableCell>
                    <TableCell align="right">{version}</TableCell>
                  </TableRow>
                ))}
            </TableBody>
          </Table>
        </TableContainer>
        <Typography variant="body1" fontSize={11}>
          Note: Logs are reset when the backend is upgraded.
        </Typography>
        <TablePagination
          rowsPerPageOptions={[10, 25, 100]}
          labelRowsPerPage="RPP"
          component="div"
          count={logs?.length}
          rowsPerPage={rowsPerPage}
          page={page}
          onPageChange={handleChangePage}
          onRowsPerPageChange={handleChangeRowsPerPage}
        />
      </Section>
    </Section>
  )
}

export default Logs
